### ISSUE TITLE
Running TODO List

### ISSUE THREAD

**Issue by darkdrgn2k** [darkdrgn2k/ssb-web-pi#1]
- [X] Install script for PI
- [X] Ability to create an account
  - [X] Generate ssb identity per user
  - [X] Create L/P and associate with the identify
  - [X] SHA256 hash password so they are not stored Clear Text
- [X] Login with login and password
  - [X] Load SSB Identiy based on L/P
- [X] View Feed
  - [X] Render Feed from JSON to HTML
  - [ ] Sort by date Descending
  - [ ] Filter stream better for logged in user
  - [ ] Figure out how to deal with Identities (Names to Pub Key)
- [X] Post Message
  - [ ] Allow MD Markup
- [ ] Allow to change Name

**Comment by darkdrgn2k** [comment]
Install script for pi:
https://cryptpad.fr/code/#/1/view/Jbjxm75vqQGlGooEFN-zww/qgAGVvxBJ3o400YDx-kAOe7l8idMmGZYpoRH3kfrKOA/
